config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: ''
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-salmon-earwig.sh
        container: qc.acc_lanky-cyan-uakari
  QC.Doc:
    repos:
      this_repo:
        commands:
        - markdownlint --json .
        - find_readme.py
        container: qc.doc_cheeky-mustard-wolverine
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-amethyst-chin.sh
        container: qc.lic_woozy-white-grasshopper
timeout: 600
