config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-orange-meerkat.sh
        container: qc.acc_freaky-pink-macaw
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-pink-manatee.sh
        container: qc.doc_foggy-gamboge-bulldog
      github.com/EOSC-synergy/sqaaas-web__2:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-coral-woodpecker.sh
        container: qc.doc_nippy-firebrick-badger
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-blue-coyote.sh
        container: qc.lic_homely-eggplant-argentino
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-zucchini-mastiff.sh
        container: qc.met_clammy-turquoise-gar
timeout: 600
