config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: ''
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-lemon-centipede.sh
        container: qc.acc_zippy-myrtle-hummingbird
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-khaki-antelope.sh
        container: qc.doc_sunny-denim-seal
  QC.Doc06:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - ls github.com/EOSC-synergy/sqaaas-web/README*
        container: qc.doc_sunny-denim-seal
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-denim-spoonbill.sh
        container: qc.lic_greasy-peach-forest
timeout: 600
