config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-charcoal-cassowary.sh
        container: qc.acc_hazy-chocolate-grasshopper
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-platinum-liger.sh
        container: qc.doc_queasy-ivory-urchin
      github.com/EOSC-synergy/sqaaas-web__2:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-dandelion-antelope.sh
        container: qc.doc_cheeky-charcoal-booby
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-pink-kingfisher.sh
        container: qc.lic_nerdy-razzmatazz-chihuahua
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-amethyst-russel.sh
        container: qc.met_wiggy-thistle-hamster
timeout: 600
