config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: ''
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-lilac-cougar.sh
        container: qc.acc_grumpy-corn-tiger
  QC.Doc:
    repos:
      this_repo:
        commands:
        - markdownlint --json .
        - find_readme.py
        container: qc.doc_frumpy-buff-orangutan
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-coral-boar.sh
        container: qc.lic_thirsty-xanthic-maltese
timeout: 600
