config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-gamboge-neanderthal.sh
        container: qc.acc_skanky-sangria-shrew
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-green-moose.sh
        container: qc.doc_craggy-tomato-avocet
      github.com/EOSC-synergy/sqaaas-web__2:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-corn-caiman.sh
        container: qc.doc_beady-ecru-abyssinian
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cinnamon-capybara.sh
        container: qc.lic_woolly-cinnabar-crab
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cardinal-guppy.sh
        container: qc.met_seedy-platinum-zebu
      github.com/EOSC-synergy/sqaaas-web__2:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-tomato-stoat.sh
        container: qc.met_flimsy-purple-ragdoll
timeout: 600
