config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: ''
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-smalt-fox.sh
        container: qc.acc_geeky-scarlet-beaver
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-brown-badger.sh
        container: qc.doc01_crabby-rose-wolf
      github.com/EOSC-synergy/sqaaas-web_sleepy:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-cardinal-crab.sh
        container: qc.doc02_sleepy-cobalt-corgi
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-azure-vulture.sh
        container: qc.lic_blurry-indigo-drever
timeout: 600
