config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: ''
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-eggplant-liger.sh
        container: qc.acc_gamy-crimson-echidna
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-lime-hippopotamus.sh
        container: qc.doc_gummy-harlequin-termite
      github.com/EOSC-synergy/sqaaas-web__2:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cinnabar-coyote.sh
        container: qc.doc_messy-auburn-dhole
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-periwinkle-olm.sh
        container: qc.lic_flimsy-scarlet-tetra
timeout: 600
