config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: ''
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-lime-orangutan.sh
        container: qc.acc_wiggy-wisteria-skunk
  QC.Doc:
    repos:
      this_repo:
        commands:
        - markdownlint --json .
        - find_readme.py
        container: qc.doc_bumpy-indigo-jaguar
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-taupe-burmese.sh
        container: qc.lic_sloppy-red-weasel
timeout: 600
