config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      branch: master
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-firebrick-terrier.sh
        container: qc.acc_skimpy-linen-worm
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-blue-maltese.sh
        container: qc.doc_cranky-chestnut-tzu
      github.com/EOSC-synergy/sqaaas-web__2:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-russet-macaque.sh
        container: qc.doc_shabby-scarlet-lemming
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-pumpkin-beaver.sh
        container: qc.lic_shaky-violet-crane
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-brown-ostrich.sh
        container: qc.met_messy-saffron-saola
timeout: 600
