config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/EOSC-synergy/sqaaas-web:
      repo: https://github.com/EOSC-synergy/sqaaas-web.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-white-vole.sh
        container: qc.acc_gimpy-magnolia-snake
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-khaki-cuttlefish.sh
        container: qc.doc_sleazy-harlequin-burmese
      github.com/EOSC-synergy/sqaaas-web__2:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-malachite-boar.sh
        container: qc.doc_skinny-teal-chicken
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-denim-chin.sh
        container: qc.lic_slimy-coral-gerbil
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-web:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-apricot-dhole.sh
        container: qc.met_breezy-viridian-ladybird
timeout: 600
